title: Documenti 42
description: Dove programmare è la risposta a tutto
remote_theme: pmarsceill/just-the-docs
baseurl: "/Documenti_42/"
url: "https://alessandrometta.github.io"
logo: "https://profile.intra.42.fr/assets/42_logo-7dfc9110a5319a308863b96bda33cea995046d1731cebb735e41b16255106c12.svg"

color_scheme: dark
