title: Documenti 42
description: Dove programmare è la risposta a tutto
author: Alessandro Metta
baseurl: "/Documenti_42/"
url: "https://alessandrometta.github.io"

remote_theme: pmarsceill/just-the-docs
color_scheme: dark
