title: Documenti 42
description: "Dove programmare è la risposta a tutto"
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  collections:
    docs:
      name: Documentation
